### ISSUE TITLE
Add logout confirm dialog

### ISSUE THREAD

**Issue by Listopia-Official** [Listopia-Official/listopia-user-and-company-administration-system#120]

**Comment by 007Cat24** [comment]
Hallo, braucht ihr Hilfe beim Projekt? Ich kann bei beim Front-End und bei Programmen in Node.js/Python helfen.
Grüße aus Berlin,
Adrian

**Comment by Listopia-Official** [comment]
Hallo,
erst einmal vielen Dank für ihr Angebot. Wir benötigen momentan keine Hilfe. Darf ich sie (aus Interesse) fragen, wie sie auf diese Repository aufmerksam geworden sind?
Viele Grüße,
Florian Haas

**Comment by 007Cat24** [comment]
Guten Abend,

Ich bin ein Schüler auf einem Gymnasium in Berlin und habe nach SaS gesucht, da dies möglicherweise ein interessanter Vorschlag für die SV sei. Mir fiel Ihre Website auf, die recht umfangreich ist und auch einen Verweis zu dieser Repo enthielt. Ich erwäge auch für unsere Schule ein solches System zu entwickeln, welches auch Hardware-Komponenten (z.B. in Form von digitalen Ausweisen mit RFID-Tags, die mit Arduinos/RasPis gescannt werden können oder auch beantragbare Kreditkarten für Wareneinkäufe etc.) enthält.
Daher finde ich es interessant, solch ein System zu sehen und die Entwicklung zu verfolgen, auch wie es bei den anderen Schülern ankommt.
MfG,
Adrian

**Comment by Listopia-Official** [comment]
Ich empfehle ihnen auf jeden Fall, SaS der SMV ihrer Schule vorzuschlagen. Wir führen SaS bereits zum zweiten Mal an unserer Schule durch, und es kam (bzw. kommt) jedes Mal sehr gut bei der Schülerschaft an. Falls sie weitere Fragen zum Projekt haben sollten, dürfen sie diese gerne stellen.

**Comment by 007Cat24** [comment]
Das ist schön zu hören :)
Ich werde nach den Osterferien in der SV darüber sprechen. Ich hätte noch einige Fragen:
- Hatten sie geprägte (Plastik-)Münzen eingesetzt? Oder doch Papierscheine?
- Sollten Unternehmen mit kleinem Umsatz gefördert werden, auch wenn sie nicht wichtig sind? Oder sollte man solche Unternehmen auflösen,
- Welche Projektdauer ist zu empfehlen? Und kann es auch an einem Tag am Samstag stattfinden?

Vielen Dank auch für Ihre anderen Antworten,

Adrian

**Comment by Listopia-Official** [comment]
- Wir setzen Papierscheine ein, zusätzlich dazu gibt es ein Banksystem mit Konten (jeder Schüler/Lehrer besitzt ein Konto).
- Diese Frage ist relativ schwierig zu beantworten. Wir verbieten prinzipiell keine Unternehmen, sondern versuchen sogar, die Schüler durch Steuererlässe etc. dazu zu bewegen, solche zu gründen, da wir momentan einen Mangel an Betrieben haben. Aber natürlich wollen wir nachher nicht nur "kleine" Betriebe haben. Daher muss dies sorgfältig abgewägt werden, und kommt nachher ganz auf die Schülerschaft bzw. die Betriebe, die davon angemeldet wurden, an.
- Unser Projekt dauert vier Tage (keine Wochenendtage); allerdings ist darin auch eine Eröffnungs- und Abschlussfeier inbegriffen. Eine Empfehlung kann ich nicht wirklich geben, aber natürlich sollte das Projekt nicht zu kurz sein. Die Projektdauer wurde bei uns von der GLK festgelegt, was bei euch wahrscheinlich nicht anders sein wird. Auch die Frage, ob das Projekt samstags stattfinden kann, müsst ihr mit dieser erörtern.

**Comment by Listopia-Official** [comment]
Dieses Issue wird bald mit einem Commit geschlossen werden. Falls sie weitere Fragen haben sollten, können sie woanders weiterschreiben.
